version: '3.8'

services:
  db:
    image: mariadb:10.5.25
    container_name: mariadb_1
    env_file:
      - ./envs/db.env
    ports:
      - "3306:3306"
#    volumes:
#      - db_data:/var/lib/mysql

  web:
    build:
      dockerfile: Dockerfile
    container_name: app_1
    ports:
      - "8000:80"
    env_file:
      - ./src/app/.env
    depends_on:
      - db


#volumes: # ignoring volumes because clean state of db needed at the current state
#  db_data: