version: '3.8'

services:
  db:
    image: mariadb:10.5.25
    container_name: mariadb_1
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: poodle
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
#    volumes:
#      - db_data:/var/lib/mysql

  web:
    build:
      dockerfile: Dockerfile
    container_name: app_1
    ports:
      - "8000:80"
    env_file:
      - ./src/app/.env
    depends_on:
      - db


#volumes:
#  db_data: