version: '3.8'

services:
  db:
    image: mariadb:10.5.25
    container_name: mariadb
    environment:
#      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: poodle
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: api
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: poodle

volumes:
  db_data: